pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'SS05_HW03_IT214_TruongHaCamLinh_PTIT056'

include 'discovery-server'
include 'product-service'
include 'api-gateway'
